spring.application.name=cadastroAnimais

# Define o profile que ele ira subir a api, nesse caso criamos só um arquivo de profile, podendo criar um para cada ambiente dev, homol e prod.
spring.profiles.active=dev
