# Gera o banco utilizando as anotações das entidades Java (@Entity, @Column, etc.).
# Gera um script SQL automaticamente.
# Define o nome do arquivo SQL.
# Coloca um delimitador ao final de cada comando SQL.

# Por ordem, a parte de cima explica o que cada linha abaixo faz, respectivamente.
# Retirar os comentários para gerar o script e comentar novamente após a geração.

#spring.jpa.properties.javax.persistence.schema-generation.create-source=metadata
#spring.jpa.properties.javax.persistence.schema-generation.scripts.action=create
#spring.jpa.properties.javax.persistence.schema-generation.scripts.create-target=create.sql
#spring.jpa.properties.hibernate.hbm2ddl.delimiter=;

# Controla quem cria e altera o banco. none = Hibernate não cria nada.
spring.jpa.hibernate.ddl-auto=none

# Define as configurações de conexão com o banco de dados. Neste caso, utilizaremos o H2 Console.
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=

# Ativa a interface do H2 Console e define o caminho para acessá-la.
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console