--liquibase formatted sql

--changeset axel:001

create table tb_ave (is_voa boolean not null, id bigint generated by default as identity, tutor_id bigint unique, classificacao varchar(255), cor_pena varchar(255), idade_animal varchar(255), nome_animal varchar(255), tipo_animal varchar(255), primary key (id));
create table tb_endereco (bairro varchar(255), cep varchar(255) not null, logradouro varchar(255), uf varchar(255), primary key (cep));
create table tb_mamifero (id bigint generated by default as identity, tutor_id bigint unique, classificacao varchar(255), cor_pelo varchar(255), idade_animal varchar(255), nome_animal varchar(255), tamanho_pelo varchar(255), tipo_animal varchar(255), primary key (id));
create table tb_repteis (id bigint generated by default as identity, tutor_id bigint unique, classificacao varchar(255), cor_da_estrutura varchar(255), idade_animal varchar(255), nome_animal varchar(255), quantidade_patas varchar(255), tipo_animal varchar(255), tipo_estrutura_externa varchar(255), primary key (id));
create table tb_tutor (id bigint generated by default as identity, endereco_id varchar(255) unique, nome_tutor varchar(255), telefone_tutor varchar(255), primary key (id));
alter table if exists tb_ave add constraint FK425j8ua78s3vfgl812ypyoalr foreign key (tutor_id) references tb_tutor;
alter table if exists tb_mamifero add constraint FKsyny8f2xk1d0lhmeienn2rhnu foreign key (tutor_id) references tb_tutor;
alter table if exists tb_repteis add constraint FKg3103691b0bkele04vj4gtj5f foreign key (tutor_id) references tb_tutor;
alter table if exists tb_tutor add constraint FKtmbwfqn3ois1bn8i2kax2p3d4 foreign key (endereco_id) references tb_endereco;


